obstacle_range: 2.5
raytrace_range: 3.0

footprint: [[-0.24,-0.20], [-0.24,0.20],[0.24,0.20],[0.24,-0.20]]
#robot_radius: ir_of_robot
inflation_radius: 0.25

#observation_sources: laser_scan_sensor
#laser_scan_sensor: {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /LaserScan}

