local_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0


    static_map: false
    rolling_window: true
    width: 10.0
    height: 10.0
    resolution: 0.05

    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        # - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    static_layer:
        enabled:              true
        map_topic:            "/map"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  2  
        inflation_radius:     0.1

    # obstacle_layer:
    #     observation_sources: laser_scan_sensor
    #     footprint_clearing_enabled: true
    #     laser_scan_sensor: {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /LaserScan}
          
