<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="4wheelrobot">


  <!-- Color Macros -->
  <material name="red">
    <color rgba="1.0 0 0 1.0"/>
  </material>
  <material name="blue">
    <color rgba="0.3 0.57 1. 1."/>
  </material>


  <!-- Base Properties -->
  <xacro:property name="body_length" value="0.3" />
  <xacro:property name="body_width" value="0.3" />
  <xacro:property name="body_height" value="0.1" />
  <xacro:property name="ground_offset" value="0.04" />
 
  <!-- Wheel Properties -->
  <xacro:property name="wheelbase" value="0.3" />
  <xacro:property name="wheel_radius" value="0.07" />
  <xacro:property name="wheel_length" value="0.03" />


  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="${wheelbase/2} 0 ${ground_offset+body_height/2}" />
        <geometry>
          <box size="${body_length} ${body_width} ${body_height}"/>
        </geometry>
    </collision>
  </link>


  <!-- Front Left Wheel-->
    <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_front_left_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="0.12 0.17 0"/>
  </joint>


  <!-- Front Right Wheel -->
    <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_front_right_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="0.12 -0.17 0"/>
  </joint>


    <!-- Back Left Wheel-->
  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_back_left_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <origin xyz="-0.12 0.17 0"/>
  </joint>


  <!-- Back Right Wheel-->
  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
      </geometry>
      <material name="red"/>
      <origin rpy="${pi/2} 0 0"/>
    </visual>
  </link>
  <joint name="base_to_back_right_wheel" type="fixed">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <origin xyz="-0.12 -0.17 0"/>
  </joint>


  <!-- Distance sensor Left-->
  <link name="left_distance_sensor">
  </link>
  <joint name="base_to_left_distance_sensor" type="fixed">
    <parent link="base_link"/>
    <child link="left_distance_sensor"/>
    <origin xyz="0.13 0.06 0" rpy="0 0 0.3"/>
    <!-- <origin rpy="1.57 1.57 -1.57"/> -->
  </joint>

  <!-- Distance sensor Right-->
  <link name="right_distance_sensor">
  </link>
  <joint name="base_to_right_distance_sensor" type="fixed">
    <parent link="base_link"/>
    <child link="right_distance_sensor"/>
    <origin xyz="0.13 -0.06 0" rpy="0 0 -0.3"/>
  </joint>

  <!-- Lidar above on base_link-->
  <link name="lidar">
  </link>
  <joint name="base_to_lidar" type="fixed">
    <parent link="base_link"/>
    <child link="lidar"/>
    <origin xyz="0.09 0 0.08"/>
  </joint>

  <!-- nav_link of type "continuous"-->
  <link name="nav_link">
  </link>
  <joint name="base_to_nav_link" type="fixed">
    <parent link="base_link"/>
    <child link="nav_link"/>
  </joint>

  <!-- IMU link on base_link-->
  <link name="imu">
  </link>
  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu"/>
    <origin xyz="0 0 0"/>
  </joint>

  <!-- GPS link on base_link-->
  <link name="gps">
  </link>
  <joint name="base_to_gps" type="fixed">
    <parent link="base_link"/>
    <child link="gps"/>
    <origin xyz="0 0 0"/>
  </joint>


</robot>
